# Generated by Django 4.2.20 on 2025-05-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
