# Generated by Django 4.2.20 on 2025-05-05 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(db_column='role_name', max_length=200),
        ),
        migrations.RenameField(
            model_name='role',
            old_name='role_name',
            new_name='roleName',
        ),
    ]
